# Generated by Django 2.2.6 on 2020-01-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='referrals',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
