# Generated by Django 2.2.6 on 2020-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200105_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='referrals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
