# Generated by Django 2.2.6 on 2020-01-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_referrals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='referrals',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
