# Generated by Django 2.2.6 on 2020-01-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200105_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referrals',
            field=models.IntegerField(default=0),
        ),
    ]
